name: TowardsLife
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  get: 3.24.0
  hive_flutter: 0.3.1
  hive: 1.4.4+1
  flutter_hooks: 
  get_storage:
  cloud_firestore: 0.14.4
  firebase_core: 0.5.3
  flutter:
    sdk: flutter
  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  device_preview:
  lint:
  test:
  flutter_launcher_icons: "^0.7.5"
  flutter_launcher_name: "^0.0.1"

flutter_launcher_name:
  name: "Towards Life"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/tl.png"

flutter:
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/jsons/

  fonts:
    - family: NotoSansTamil
      fonts:
        - asset: assets/fonts/NotoSansTamil-Regular.ttf
        - asset: assets/fonts/NotoSansTamil-Bold.ttf
          weight: 700
    - family: ArimaMadurai
      fonts:
        - asset: assets/fonts/ArimaMadurai-Regular.ttf
        - asset: assets/fonts/ArimaMadurai-Medium.ttf
          weight: 700