name: release workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.20.x' 
        channel: 'beta' # optional, default to: 'stable'
    - run: flutter pub get
    # - run: flutter test
    - name: Build
      run: |
        mkdir $HOME/private
        gpg --quiet --batch --yes --decrypt --passphrase="$FIREBASE_SECRET" \
        --output $HOME/private/services.tar services.tar.gpg
        tar xvf $HOME/private/services.tar
        flutter build appbundle
        flutter build apk
        flutter build ios --release --no-codesign
      env:
        FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
    # - run: 

    - uses: actions/upload-artifact@v2
      with:
        name: TowardsLife-android-apk
        path: build/app/outputs/apk/release/app-release.apk

    - uses: actions/upload-artifact@v2
      with:
        name: TowardsLife-ios
        path: build/ios/iphoneos/Runner.app.
